// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaXIgDYRCEanTpWIecUKVfmhL8vN4Xu4E',
    appId: '1:1095341185716:android:cebe9f6fafe9da5c2595e1',
    messagingSenderId: '1095341185716',
    projectId: 'chat-app-e489a',
    storageBucket: 'chat-app-e489a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUeDO86dXY5tJOb8Hv4YjJ1M9kBr363L8',
    appId: '1:1095341185716:ios:d8b5f3b133d6ae472595e1',
    messagingSenderId: '1095341185716',
    projectId: 'chat-app-e489a',
    storageBucket: 'chat-app-e489a.appspot.com',
    androidClientId: '1095341185716-bko4d5jg2ag4jpb2t7pc4s6ej3ahd43r.apps.googleusercontent.com',
    iosClientId: '1095341185716-5h4dnr8q2lilhh7qo5v7qbfdue4pak8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

}