name: chat_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  #spell:ignore cupertino
  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.5
  equatable: ^2.0.5
  json_serializable: ^6.8.0
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  firebase_storage: ^11.7.7
  emoji_picker_flutter: ^2.2.0
  firebase_messaging: ^14.9.4
  http: ^1.2.1
  googleapis_auth: ^1.6.0
  flutter_notification_channel: ^3.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_gen_runner: ^5.5.0+1
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: 'ic_launcher'
  ios: true
  image_path: "packages/common/assets/images/emoji.png"
  min_sdk_android: 21
  remove_alpha_ios: true
flutter_gen:
  output: lib/generator
  line_length: 80
  assets:
    enable: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - packages/common/assets/images/
